name: Go Unit Tests
on:
  push:
    branches:
    - "*"

jobs:
  tests:
    name: Go Tests
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.GITLAB_PERSONAL_ACCESS_TOKEN }}
        USER: ${{ secrets.GITLAB_USERNAME }}
      run: git config --global url."https://${USER}:${TOKEN}@gitlab.com".insteadOf "https://gitlab.com"
    - name: Install Go 1.14
      uses: actions/setup-go@v1
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@master

    - run: make cmd-go-mod-tidy

    - name: Run tests
      run: |
        TF_ACC=1 go test -v ./... -timeout=30m